### ISSUE TITLE
About PhyloScanner Ancestry analysis tool   

### ISSUE THREAD

**Issue by manisenthils** [MarcNiebel/thesis#1]
Hello Marc, 
This is Mani. I am working in HIV-AIDS, I came to know about Phyloscanner and I wanted to do the Analysis with my Patient NGS data. I saw your comment on https://github.com/BDI-pathogens. So I thought if you know about it you can help me!
I don't know I can I contact you so I have raised an issue. I have read about the tool and also I have downloaded it and practiced with the example data they gave. as far as I know those analysis are between- host with more than one patient. And I wanted to do with-in host evolutionary Analysis with single patient NGS data. I have searched for that I couldn't able to find any examples like instructions for with-in host. So can you help me out if have done this kind of analysis!

thanks,
Manisenthil

**Comment by MarcNiebel** [comment]
Hi Mani,
Thanks for getting in touch. Unfortunately I am not a developer of this analysis tool, although I have worked with it in the past. Your best bet is to ask the developers directly and hopefully they can help.

**Comment by manisenthils** [comment]
Okay Marc , Thanks for your response. 

Thanks,
Manisenthil
